"""
ecg_model.py
============
Three-stage ECG analysis pipeline:
  Stage 1 – Load, verify, and plot the ECG waveform from MATLAB.
  Stage 2 – Normalise and segment the ECG for future LSTM training.
  Stage 3 – Define (but do NOT train) an LSTM classifier skeleton.

Compatible with Python 3.10+
"""

import sys
import os

# ===========================================================================
# Stage 0 — Imports
# ===========================================================================
try:
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
except ImportError as e:
    print(f"[ERROR] Missing required library: {e.name}")
    print("Install it with:  pip install pandas numpy matplotlib")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Absolute path to the ECG CSV produced by MATLAB
# ---------------------------------------------------------------------------
CSV_PATH = r"C:\Users\deysr\OneDrive\Desktop\IoTRICITY\ecg_signal.csv"

# ===========================================================================
# Stage 1 — Load, Verify, and Plot the ECG Signal
# ===========================================================================
print("=" * 65)
print("  STAGE 1 : Loading and Plotting the ECG Signal")
print("=" * 65)

# --- 1a. Check that the CSV file exists ----------------------------------
if not os.path.isfile(CSV_PATH):
    print(f"\n[ERROR] CSV file not found at:\n  {CSV_PATH}")
    print("Please ensure the MATLAB script has run and the file exists.")
    sys.exit(1)

# --- 1b. Read the CSV ----------------------------------------------------
try:
    df = pd.read_csv(CSV_PATH)
    print(f"\n[OK] CSV loaded successfully from:\n  {CSV_PATH}")
except Exception as e:
    print(f"\n[ERROR] Failed to read CSV: {e}")
    sys.exit(1)

# --- 1c. Verify required columns -----------------------------------------
required_columns = {"Time", "ECG"}
missing = required_columns - set(df.columns)
if missing:
    print(f"\n[ERROR] Missing column(s) in CSV: {missing}")
    print(f"  Columns found: {list(df.columns)}")
    sys.exit(1)
print(f"[OK] Required columns {required_columns} are present.")

# --- 1d. Print basic statistics -------------------------------------------
num_samples = len(df)
sampling_interval = df["Time"].iloc[1] - df["Time"].iloc[0]  # seconds
sampling_frequency = 1.0 / sampling_interval                  # Hz

print(f"\n  Number of ECG samples   : {num_samples}")
print(f"  Sampling interval (dt)  : {sampling_interval:.6f} s")
print(f"  Sampling frequency (Fs) : {sampling_frequency:.2f} Hz")
print(f"\n  First 10 ECG values:")
for i, val in enumerate(df["ECG"].iloc[:10]):
    print(f"    [{i}]  {val: .10f}")

# --- 1e. Plot the ECG waveform -------------------------------------------
plt.figure(figsize=(14, 4))
plt.plot(df["Time"], df["ECG"], linewidth=0.8, color="mediumblue")
plt.title("ECG Signal Generated by MATLAB and Received by Python", fontsize=13)
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(
    os.path.join(os.path.dirname(CSV_PATH), "ecg_waveform_plot.png"),
    dpi=150,
)
plt.show()
print("\n[OK] ECG waveform plotted and saved as 'ecg_waveform_plot.png'.\n")

# ===========================================================================
# Stage 2 — Prepare the ECG Data for Machine Learning (LSTM)
# ===========================================================================
print("=" * 65)
print("  STAGE 2 : Preparing ECG Data for LSTM Input")
print("=" * 65)

# --- 2a. Extract the ECG column as a NumPy array -------------------------
ecg_raw = df["ECG"].to_numpy(dtype=np.float32)
print(f"\n  Raw ECG array shape : {ecg_raw.shape}")

# --- 2b. Normalise the ECG signal (Min-Max to [0, 1]) --------------------
ecg_min = ecg_raw.min()
ecg_max = ecg_raw.max()
if ecg_max - ecg_min == 0:
    print("\n[WARNING] ECG signal is constant — normalisation skipped.")
    ecg_normalised = ecg_raw
else:
    ecg_normalised = (ecg_raw - ecg_min) / (ecg_max - ecg_min)
print(f"  Normalised range    : [{ecg_normalised.min():.4f}, {ecg_normalised.max():.4f}]")

# --- 2c. Segment into fixed-length sequences for LSTM --------------------
# Each sequence = one heartbeat window ≈ 1 second at ~360 Hz → 360 samples.
# Adjust SEQUENCE_LENGTH if your sampling rate or use-case differs.
SEQUENCE_LENGTH = 360  # samples per window

num_full_sequences = len(ecg_normalised) // SEQUENCE_LENGTH
trimmed = ecg_normalised[: num_full_sequences * SEQUENCE_LENGTH]

# Reshape into (num_sequences, SEQUENCE_LENGTH, 1) — LSTM expects 3-D input
sequences = trimmed.reshape(num_full_sequences, SEQUENCE_LENGTH, 1)

print(f"\n  Sequence length     : {SEQUENCE_LENGTH} samples")
print(f"  Total full sequences: {num_full_sequences}")
print(f"  Discarded tail      : {len(ecg_normalised) - len(trimmed)} samples")
print(f"  LSTM input shape    : {sequences.shape}  "
      f"(samples, timesteps, features)")

# --- 2d. Note: labels are NOT available -----------------------------------
print("\n  [!] No Normal/Abnormal labels exist in this CSV.")
print("     Sequences are prepared but CANNOT be used for supervised")
print("     training until labelled data is provided.\n")

# ===========================================================================
# Stage 3 — Define (Do NOT Train) an LSTM Classifier Skeleton
# ===========================================================================
print("=" * 65)
print("  STAGE 3 : LSTM Classifier Skeleton (Untrained)")
print("=" * 65)

# Try importing TensorFlow / Keras.  If unavailable, print the model
# architecture as pseudocode so the user still sees the intended design.
try:
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import LSTM, Dense, Dropout
    KERAS_AVAILABLE = True
except ImportError:
    KERAS_AVAILABLE = False

if KERAS_AVAILABLE:
    # Build a simple LSTM binary classifier
    model = Sequential(name="ECG_LSTM_Classifier")
    model.add(
        LSTM(
            units=64,
            return_sequences=True,
            input_shape=(SEQUENCE_LENGTH, 1),
            name="lstm_1",
        )
    )
    model.add(Dropout(0.3, name="dropout_1"))
    model.add(
        LSTM(
            units=32,
            return_sequences=False,
            name="lstm_2",
        )
    )
    model.add(Dropout(0.3, name="dropout_2"))
    model.add(Dense(1, activation="sigmoid", name="output"))

    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )

    print("\n[OK] Keras LSTM model built successfully (NOT trained).\n")
    model.summary()
else:
    # Keras is not installed -- display the intended architecture
    print("\n[INFO] TensorFlow/Keras is not installed.")
    print("       Printing the intended LSTM architecture below.\n")
    arch = """
    Model: "ECG_LSTM_Classifier"
    +--------------------------------------------------------------+
    | Layer              | Type    | Output Shape      | Params   |
    +--------------------------------------------------------------+
    | lstm_1             | LSTM    | (None, 360, 64)   | 16,896   |
    | dropout_1          | Dropout | (None, 360, 64)   | 0        |
    | lstm_2             | LSTM    | (None, 32)        | 12,416   |
    | dropout_2          | Dropout | (None, 32)        | 0        |
    | output             | Dense   | (None, 1)         | 33       |
    +--------------------------------------------------------------+
    Activation : sigmoid (binary classification)
    Loss       : binary_crossentropy
    Optimizer  : Adam
    """
    print(arch)

print("\n" + "=" * 65)
print("  NOTE")
print("=" * 65)
print("""
  This model is a SKELETON only.  It has NOT been trained because
  the current 'ecg_signal.csv' contains a synthetic ECG waveform
  without Normal / Abnormal labels.

  Next steps to train the classifier:
    1. Obtain a labelled ECG dataset (e.g., MIT-BIH from PhysioNet).
    2. Assign binary labels:  0 = Normal,  1 = Abnormal.
    3. Call  model.fit(X_train, y_train, ...)  to train.
    4. Evaluate with  model.evaluate(X_test, y_test).
""")
print("=" * 65)
print("  ecg_model.py finished successfully.")
print("=" * 65)
